# permissions for end users to view cores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: core-viewer-role
rules:
- apiGroups:
  - cardano.zenithpool.io
  resources:
  - cores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cardano.zenithpool.io
  resources:
  - cores/status
  verbs:
  - get
