# permissions for end users to view relays.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: relay-viewer-role
rules:
- apiGroups:
  - cardano.zenithpool.io
  resources:
  - relays
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cardano.zenithpool.io
  resources:
  - relays/status
  verbs:
  - get
