# permissions for end users to edit relays.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: relay-editor-role
rules:
- apiGroups:
  - cardano.zenithpool.io
  resources:
  - relays
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cardano.zenithpool.io
  resources:
  - relays/status
  verbs:
  - get
